# Generated by Django 3.2.18 on 2023-11-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acno', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('depamnt', models.IntegerField()),
                ('bal', models.IntegerField()),
            ],
        ),
    ]
